services:
  postgres:
    image: postgres:16.9
    container_name: agora-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agora-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: ${IMAGE_TAG:-ghcr.io/zughayyar/agora-server:latest}
    container_name: agora-migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - agora-network
    environment:
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL_MODE: disable
    command: ["./bin/migration", "-action=migrate"]
    restart: "no"

  server:
    image: ${IMAGE_TAG:-ghcr.io/zughayyar/agora-server:latest}
    container_name: agora-server
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - agora-network
    restart: unless-stopped
    environment:
      # Application Configuration
      APP_ENV: production
      APP_PORT: ${APP_PORT}
      APP_VERSION: ${APP_VERSION}
      
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL_MODE: disable
      DB_LOG_QUERIES: ${DB_LOG_QUERIES}
      
      # Database Connection Pool Configuration
      DB_MAX_OPEN_CONNS: ${DB_MAX_OPEN_CONNS}
      DB_MAX_IDLE_CONNS: ${DB_MAX_IDLE_CONNS}
      DB_CONN_MAX_LIFETIME_MINUTES: ${DB_CONN_MAX_LIFETIME_MINUTES}
      DB_CONN_MAX_IDLE_TIME_MINUTES: ${DB_CONN_MAX_IDLE_TIME_MINUTES}

volumes:
  postgres_data:

networks:
  agora-network:
    driver: bridge
